Add configuration to generate logstash friendly access logs
fabric8-ui/fabric8-ui-openshift-nginx pull request #2
Opened 2017-06-12 19:12 UTC by hectorj2f

I show an example of the output in json format:
```
{ "@timestamp": "2017-06-12T19:07:54+00:00", "@fields": { "remote_addr": "172.17.0.1", "remote_user": "-", "body_bytes_sent": "169", "request_time": "0.000", "status": "403", "request": "GET / HTTP/1.1", "request_method": "GET", "http_referrer": "-", "http_x_forwarded_for": "-", "http_user_agent": "curl/7.35.0" } }
```

whole log of the container:
```
2017/06/12 19:07:43 [notice] 18#0: using the "epoll" event method
2017/06/12 19:07:43 [notice] 18#0: nginx/1.10.2
2017/06/12 19:07:43 [notice] 18#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
2017/06/12 19:07:43 [notice] 18#0: OS: Linux 3.13.0-92-generic
2017/06/12 19:07:43 [notice] 18#0: getrlimit(RLIMIT_NOFILE): 524288:1048576
2017/06/12 19:07:43 [notice] 18#0: start worker processes
2017/06/12 19:07:43 [notice] 18#0: start worker process 19
2017/06/12 19:07:54 [error] 19#0: *1 directory index of "/usr/share/nginx/html/" is forbidden, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost:8086"
{ "@timestamp": "2017-06-12T19:07:54+00:00", "@fields": { "remote_addr": "172.17.0.1", "remote_user": "-", "body_bytes_sent": "169", "request_time": "0.000", "status": "403", "request": "GET / HTTP/1.1", "request_method": "GET", "http_referrer": "-", "http_x_forwarded_for": "-", "http_user_agent": "curl/7.35.0" } }
2017/06/12 19:07:54 [info] 19#0: *1 client 172.17.0.1 closed keepalive connection
```

2017-06-12 19:28 UTC, hectorj2f commented
ping @aslakknutsen

2017-06-13 00:38 UTC, aslakknutsen requested changes

2017-06-13 00:38 UTC, aslakknutsen commented on root/etc/nginx/nginx.conf
> +    log_format logstash_json '{ "@timestamp": "$time_iso8601", '
Add escape=json

2017-06-13 09:43 UTC, hectorj2f commented on root/etc/nginx/nginx.conf
> +    log_format logstash_json '{ "@timestamp": "$time_iso8601", '
@aslakknutsen done

2017-06-15 12:26 UTC, hectorj2f commented
ping @aslakknutsen

2017-07-05 10:05 UTC, aslakknutsen approved these changes

2017-07-05 10:16 UTC, aslakknutsen commented
@joshuawilson ping

2017-07-05 14:21 UTC, merged